# Introducción a Python para ciencias e ingenierías (notebook 3)


Ing. Martín Gaitán (Phasety)


![](img/logo_small.png)

--------





## Módulos y paquetes


Buenísimo estos *notebooks* pero ¿qué pasa si quiero reusar código? 

Hay que crear **módulos**. 

Por ejemplo, abramos el editor y guardemos esta función:

        
    def raices(a, b, c, margen=1e-5):
        """Dados los coeficientes a, b y c encuentra los valores de X
           que hacen aX^2 + bX + c == 0"""
        
        discriminante = b*b - 4*a*c
        a,b,c,d = complex(a), complex(b), complex(c), complex(discriminante)
        raiz1 = (-b + d**0.5)/2./a
        raiz2 = (-b - d**0.5)/2./a
        if abs(discriminante) < margen:
            # reales e iguales
            return abs(raiz1), abs(raiz1)
        if discriminante > 0:
            # reales
            return raiz1.real, raiz2.real
        # complejas
        return raiz1, raiz2


In [ ]:
!gedit cuadratica.py    # truquito para ejecutar programas desde ipython

Lo hemos guardado en un archivo `cuadratica.py` en el directorio donde estamos corriendo esta consola (notebook), entonces directamente podemos **importar** ese modulo. 

In [ ]:
import cuadratica

Esto nos crea un *"espacio de nombres"* llamado `cuadratica`, dentro del cual está la función que definimos 

In [ ]:
cuadratica.raices?

In [ ]:
cuadratica.raices(3, 2, -1)

In [ ]:
cuadratica.raices(3, 2, 1)

Importar un modulo y usarlo como prefijo **es una buena práctica** para saber dónde está realmente definido un código. No obstante hay otras maneras. A veces es util usar un alias así


In [ ]:
import cuadratica as cuad   # igual que la primera forma pero poniendole un alias (mas breve). 

cuad.raices?

Si sólo queremos alguna unidad de código y no todo el módulo, entonces podemos hacer una importación selectiva

In [ ]:
from cuadratica import raices  # sólo importa el "objeto" que indequemos y lo deja 
                               # en el espacio de nombres actual

Si, como sucede en general, el módulo definiera más de una unidad de código (una función, clase, constantes, etc.) podemos usar una tupla para importar varias cosas cosas al espacio de nombres actual. Por ejemplo:

      from cuadratica import raices, integral, diferencial 
 
Por último, si queremos importar todo pero no usar el prefijo, podemos usar el `*`. **Esto no es recomendado**
    
    from cuadratica import *

Cuando tenemos muchos módulos que están relacionados es bueno armar un **paquete**. Un paquete de modulos es un simple directorio con un módulo llamado `__init__.py` (que puede estar vacio) y tantos modulos y subpaquetes como queramos. Los paquetes se usan igual que un módulo. Por ejemplo, supongamos que tenemos una estructura

    paquete/
       __init__.py
       modulo.py

Puedo importar la `funcion_loca` definida en `modulo.py` así 

    from paquete.modulo import funcion_loca 


## Módulos y paquetes incluídos: las baterías puestas de Python

Hasta ahora vimos algunas funciones y estructuras de datos que Python ofrece sin tener que importar nada, pero sin tener que instalar ninguna biblioteca extra, cualquier versión de python trae muchos módulos y paquetes listos para usar. Es lo que se conoce como la [librería estándar de python](http://docs.python.org/2/library/) y es muy abarcativa y potente. 

Por ejemplo funciones matemáticas, manejo de algunos formatos de archivos más específicos que el "texto plano", protocolos de internet, otras *clases* de números y estructuras de datos,  etc. 

### Funciones y constantes matemáticas

In [ ]:
import math

In [ ]:
math.cos(math.pi)

In [ ]:
math.sqrt(2)

### CSV

Los CSV (comma separated values) son una forma básica pero muy extendida de intercambiar información estructurada entre distintos programas. Por ejemplo, desde Excel o Libreoffice Calc se pueden guardar (y abrir) archivos CSV. y python también sabe. 


In [ ]:
%less data/near_critical_oil.csv   # cuando algo empieza con % es "magia" de ipython (no funcionan en python puro)
                                   # ver %magic para más datos

In [ ]:
import csv
reader = csv.reader(open('data/near_critical_oil.csv'))
critical_oil = [line for line in reader]
critical_oil

### Otros módulos interesantes para ver

- json: serialización de objetos en formato JSON (muy comun en "servicios web")
- random: aleatoridad (numeros, funciones)
- os: acceso al sistema operativo (directorios, archivos, etc)
- y mucho ¡mucho! más http://docs.python.org/2/library/


## Matplotlib, un gráfico vale más que mil palabras

Python es un lenguaje muy completo pero aunque es muy grande, su librería estándar no es infinita. Por suerte hay miles y miles de bibliotecas extra para complementar casi cualquier aspecto en el que queramos aplicar Python. En algunos ámbitos, con soluciones muy destacadas. 

Para hacer gráficos existe Matplotlib http://matplotlib.org/ . Ya viene instalado con la versión completa de Anaconda. 


In [ ]:
%matplotlib inline

In [ ]:
from matplotlib import pyplot

In [ ]:
x = [0.1*i for i in range(-50, 51)]
y = [x_i**2 for x_i in x]

In [ ]:
pyplot.plot(x,y)

Los gráficos emergentes son buenos porque tiene la barra de herramientas y podemos guardarlos en excelente calidad (incluso vectorial, ideal para un poster A0). Pero en los notebooks podemos poner los gráficos directamente incrustados

In [ ]:
pyplot.plot(x,y)
pyplot.title('Pará bola!')
pyplot.grid()

Matplotlib sabe hacer muchísimos tipos de gráficos!

In [ ]:
components = [c for (c, f) in critical_oil[1:]]
fraction = [float(f) for (c, f) in critical_oil[1:]]
# el ; evita el output
pyplot.pie(fraction, labels=components, shadow=True);

In [ ]:
import random
campana = [random.gauss(0, 0.5) for i in range(1000)]

In [ ]:
pyplot.hist(campana, bins=15);

Pero antes de seguir con Matplotlib debemos aprender el corazón del Python Cientifico: Numpy

## Numpy, todo es un array

El paquete **numpy** es usado en casi todos los cálculos numéricos usando Python. Es un paquete que provee a Python de estructuras de datos vectoriales, matriciales y de rango mayor, de alto rendimiento. Está implementado en C y Fortran, de modo que cuando los cálculos son vectorizados (formulados con vectores y matrices), el rendimiento es muy bueno.

In [ ]:
import numpy as np

El pilar de numpy (y toda la computación científica basada en Python) es el tipo de datos `ndarray`, o sea arreglos de datos multidimensionales. 

¿Otra secuencia más? ¿pero que tenina de malo las listas?

Las listas son geniales pero guardar **cualquier tipo de objeto** y su flexibilidad las vuelve ineficientes

In [ ]:
%timeit [0.1*i for i in range(10000)]    # %timeit es otra magia de ipython

In [ ]:
%timeit np.arange(0, 1000, .1)    # arange es igual a range, pero soporta paso de tipo flotante

Existen varias formas para inicializar nuevos arreglos de numpy, por ejemplo desde

- Listas o tuplas
- Usando funciones dedicadas a generar arreglos numpy, como `arange`, `linspace`,`ones`, `zeros` etc.
- Leyendo datos desde archivos

In [ ]:
v = np.array([1,2,3,4])
v

In [ ]:
# una matriz: el argumento de la función array function es una lista anidada de Python
M = np.array([[1, 2], 
              [3, 4]])
M

In [ ]:
type(v), type(M)

Los ndarrays tienen distintos atributos. Por ejemplo

In [ ]:
v.ndim, M.ndim    # cantidad de dimensiones

In [ ]:
v.shape, M.shape  # tupla de "forma". len(v.shape) == v.ndim

In [ ]:
v.size, M.size   # cantidad de elementos. 

In [ ]:
M.T   # transpuesta!

A diferencia de las listas, los *arrays* tambien **tienen un tipo homogéneo** 

In [ ]:
v.dtype     # 

Se puede definir explicitamente el tipo de datos del array

In [ ]:
np.array([[1, 2], [3, 4]], dtype=complex)

Una gran ventaja del atributo `shape` es que podemos cambiarlo. Es decir, reacomodar la distrución de los elementos (por supuesto, sin perderlos en el camino)

In [ ]:
A = np.arange(0, 12)
print(A)

In [ ]:
A.shape = 3, 4
print(A)

Esto es porque numpy en general no mueve los elementos de la memoria y en cambio usa **vistas** para mostrar los elementos de distinta forma. Es importante entender esto porque incluso los slicings son vistas. 

In [ ]:
a = np.arange(10)
b = a[::2]  # todo de 2 en 2
b

In [ ]:
b[0] = 12
a  # chan!!!

En cambio

In [ ]:
a = np.arange(10)
b = a[::2].copy()
b[0] = 12
a

Además de `arange` hay otras funciones que devuelven arrays. Por ejemplo `linspace`, que a diferencia de `arange` no se da el tamaño del paso, sino la cantidad de puntos que queremos en el rango

In [ ]:
np.linspace(0, 2 * np.pi, 100)      # por defecto, incluye el limite. 

In [ ]:
_.size   # en cualquier consola, python guarda el ultimo output en la variable _ 

In [ ]:
matriz_de_ceros = np.zeros((4,6))
matriz_de_ceros

In [ ]:
np.ones((2, 4))

Pero numpy no sólo nos brinda los arrays. Los conceptos claves que aporta son *vectorización* y *broadcasting*

La **vectorización** describe la **ausencia de iteraciones explícitas e indización**
(que toman lugar, por supuesto, "detrás de escena", en un optimizado y precompilado
código C). La vectorización tiene muchas ventajas:

* El código vectorizado es más conciso y fácil de leer.
* Menos líneas de código habitualmente implican menos errores.
* El código se parece más a la notación matemática estándar (por lo que es más fácil,
por lo general, corregir código asociado a construcciones matemáticas
* La vectorización redunda en un código más "pythónico"

In [ ]:
a = np.array([3, 4.3, 1])
b = np.array([-1, 0, 3.4])
c = a * b
c

¡Basta de bucles `for` for todos lados! 

El **broadcasting** (*difusión*) es el término que describe el comportamiento
**elemento por elemento** de las operaciones. En general, en Numpy todas
las operaciones adoptan por defecto un comportamiento de este tipo (no sólo las operaciones
aritméticas sino las lógicas, las funcionales y las de nivel de bits). 

In [ ]:
x = np.linspace(-12, 12, 1000)
y = x ** 2 - 1
pyplot.plot(x, y)

Matplotlib se lleva muy bien con numpy (de hecho lo usa internamente)

### Slicing extendido

El funcionamiento básico del indexado y el slicing funciona igual con `ndarrays` que con cualquier secuencia.  


In [ ]:
ruido = np.random.random(1000)   # 1000 numeros aleatorios entre [0, 1)


In [ ]:
ruido[0] == ruido[-1000]

In [ ]:
ruido[999] == ruido[-1]

In [ ]:
ruido[1:5]

In [ ]:
ruido[0:10] = np.zeros((10,))  # claro que los arrays son mutables!

Pero veamos algo más. Supongamos que tenemos una matriz de 3x3

In [ ]:
m = np.arange(0, 9)  
m.shape = 3, 3
m

In [ ]:
m[0]       # primer indice: filas

In [ ]:
m[0:2]

Pero la sintaxis se extiende de una manera eficiente y compacta.



In [ ]:
%timeit m[1][1]      # buuuuh!!!

In [ ]:
%timeit m[1,1]    # yeaaaa!!!

In [ ]:
m[:,0]      # quiero la primer columna

In [ ]:
m[0:2, 0:2]   # la submatriz superior izquierda de 2x2 

Se acuerdan que en el slicing común había un tercer parametro opcional que era el paso? Funciona acá también

In [ ]:
m[::2, ::2]    # esquinas

In [124]:
a = np.arange(60)
a.shape = 6, 10
a[:,:6]



array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [126]:
a[:,2:3]h

array([[ 2],
       [12],
       [22],
       [32],
       [42],
       [52]])

Como resumen

![](http://www.tp.umu.se/~nylen/pylect/_images/numpy_indexing.png)


### Ejercicios

- Crear un array de 1000 números aleatorios y encontrar su media (tip: ver el método `mean()`)
- Crear una array (matriz) de 10x10 donde cada fila va del 0 al 9 (tip: ¿qué pasa al sumar un array 2d con otro 1d?)
- Crear una matriz de esta forma

        array([[0, 0, 0, 0, 5],
               [0, 0, 0, 4, 0],
               [0, 0, 3, 0, 0],
               [0, 2, 0, 0, 0],
               [1, 0, 0, 0, 0]])
  (tip: investigar la función `diag()` y `rot90()`


In [131]:
aleatorio = np.random.normal?

In [ ]:
aleatorio = np.random.normal

In [135]:
np.zeros((10,10)) + np.arange(10)

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]])

### Algunas funciones incluídas en numpy

Encontrar raices de un polinomio

In [136]:
np.roots([2, 0, -2])

array([-1.,  1.])

In [137]:
np.roots([1j, -4+0.4j, 18, -np.pi, 0])  # polinomio de grado 5!

array([-3.01556495 -5.38277801e+00j,  2.43369801 +1.38394115e+00j,
        0.18186694 -1.16314504e-03j,  0.00000000 +0.00000000e+00j])

Resolver un sistema de ecuaciones lineales  `Ax = b`

In [138]:
A = np.array([[1, 2], [0.5, -2]])
b = np.array([4, 5.2])

In [139]:
x = np.linalg.solve(A, b)
x

array([ 6.13333333, -1.06666667])

Encontrar la inversa de una matriz

In [ ]:
A = np.array([[1,2],[3,4]])
invA = np.linalg.inv(A)
invA

In [ ]:
np.dot(A,invA)   # producto punto

### Ejercicios

- Encontrar las raices para el polinomio $$f(x) = \frac{1}{4}(x^3 + 3x^2 − 6x − 8)$$ y grafique con x entre [-3, 3]
- Resuelva el siguiente sistema de ecuaciones 

  $$\begin{array} - -x + z = -2\\ 2x - y + z = 1 \\ -3x + 2y -2z = -1 \\ x - 2y + 3z = -2 \end{array}$$

